name: build @monorepo/client

on:
  push:
    branches:
      - master
    paths:
      - 'packages/web/**'
      - 'packages/shared/axios-config/**'
      - 'packages/shared/babel-preset-monorepo/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Deploy
        run: echo "Done!"
